### ISSUE TITLE
Installation fails on Elementary OS Loki (Ubuntu 16.04)

### ISSUE THREAD

**Issue by tobias-kuendig** [jmarcher/valet-linux#25] opened 2016-09-17 17:26 UTC
After running `valet install` I am prompted for the sudo password. Then the following error happens:

> PHP Fatal error:  Cannot declare class Brew, because the name is already in use in /home/user/.composer/vendor/jmarcher/valet-linux/cli/includes/facades.php on line 31

**Comment by mehrancodes** [comment] 2016-09-19 09:18
Conflict of illuminate/support library with valet is the cause of this error.
the [pull request](https://github.com/jmarcher/valet-linux/pull/26) should be merged soon....

**Comment by jmarcher** [comment] 2016-09-19 13:20
Merged

**Closed as completed** 2016-10-30 06:29 UTC
